import { PERMISSIONS } from "@/constants";
import type { IUserLogged } from "./auth.types";
import { ROLE } from "@/constants/role";

export const fakeUsers: Record<string, IUserLogged> = {
  ADMIN: {
    id: 1,
    username: "admin",
    email: "admin@example.com",
    phone: "0987654321",
    gender: 1,
    dob: "1998-06-15",
    address: "Hà Nội, Việt Nam",
    status: 1,
    fullname: "Quản trị viên hệ thống",
    type: 0,
    createdBy: "system",
    createdDate: "2024-01-01T00:00:00Z",
    lastModifiedBy: null,
    lastModifiedDate: null,
    roles: [ROLE.SUPER_ADMIN],
    permissions: [PERMISSIONS.SUPER_ADMIN], // SUPER_ADMIN có quyền tất cả
  },

  MANAGER: {
    id: 2,
    username: "manager",
    email: "manager@example.com",
    phone: "0987654322",
    gender: 1,
    dob: "1995-03-20",
    address: "Hà Nội, Việt Nam",
    status: 1,
    fullname: "Quản lý",
    type: 0,
    createdBy: "system",
    createdDate: "2024-01-01T00:00:00Z",
    lastModifiedBy: null,
    lastModifiedDate: null,
    roles: [ROLE.MANAGER],
    permissions: [
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.USER_READ,
      PERMISSIONS.PRODUCT_READ,
      PERMISSIONS.ORDER_READ,
      PERMISSIONS.PRODUCT_CATEGORY_READ,
      PERMISSIONS.NOTIFICATION_READ,
      PERMISSIONS.REPORT_VIEW,
    ],
  },

  HR: {
    id: 3,
    username: "hr",
    email: "hr@example.com",
    phone: "0987654323",
    gender: 1,
    dob: "1992-11-10",
    address: "Hà Nội, Việt Nam",
    status: 1,
    fullname: "Nhân sự",
    type: 0,
    createdBy: "system",
    createdDate: "2024-01-01T00:00:00Z",
    lastModifiedBy: null,
    lastModifiedDate: null,
    roles: [ROLE.HR],
    permissions: [
      PERMISSIONS.USER_READ,
      PERMISSIONS.USER_CREATE,
      PERMISSIONS.USER_UPDATE,
      PERMISSIONS.USER_DELETE,
      PERMISSIONS.ROLE_READ,
    ],
  },
};
