export enum PERMISSIONS {
  /** 👑 Quyền toàn hệ thống */
  SUPER_ADMIN = "SUPER_ADMIN",

  /** 🏠 Dashboard */
  DASHBOARD_VIEW = "DASHBOARD_VIEW",

  /** 👥 Quản lý người dùng */
  USER_CREATE = "USER_CREATE",
  USER_READ = "USER_READ",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",

  /** 🛍️ Quản lý sản phẩm */
  PRODUCT_CREATE = "PRODUCT_CREATE",
  PRODUCT_READ = "PRODUCT_READ",
  PRODUCT_UPDATE = "PRODUCT_UPDATE",
  PRODUCT_DELETE = "PRODUCT_DELETE",

  /** 📦 Quản lý danh mục sản phẩm */
  PRODUCT_CATEGORY_CREATE = "PRODUCT_CATEGORY_CREATE",
  PRODUCT_CATEGORY_READ = "PRODUCT_CATEGORY_READ",
  PRODUCT_CATEGORY_UPDATE = "PRODUCT_CATEGORY_UPDATE",
  PRODUCT_CATEGORY_DELETE = "PRODUCT_CATEGORY_DELETE",

  /** 🧾 Quản lý đơn hàng */
  ORDER_CREATE = "ORDER_CREATE",
  ORDER_READ = "ORDER_READ",
  ORDER_UPDATE = "ORDER_UPDATE",
  ORDER_DELETE = "ORDER_DELETE",

  /** 📢 Quản lý thông báo */
  NOTIFICATION_CREATE = "NOTIFICATION_CREATE",
  NOTIFICATION_READ = "NOTIFICATION_READ",
  NOTIFICATION_UPDATE = "NOTIFICATION_UPDATE",
  NOTIFICATION_DELETE = "NOTIFICATION_DELETE",

  /** 📊 Báo cáo */
  REPORT_VIEW = "REPORT_VIEW",
  REPORT_EXPORT = "REPORT_EXPORT",

  /** ⚙️ Cài đặt & Phân quyền */
  ROLE_CREATE = "ROLE_CREATE",
  ROLE_READ = "ROLE_READ",
  ROLE_UPDATE = "ROLE_UPDATE",
  ROLE_DELETE = "ROLE_DELETE",

  SETTING_READ = "SETTING_READ",
  SETTING_UPDATE = "SETTING_UPDATE",
}
