export enum PERMISSIONS {
  SUPER_ADMIN = "SUPER_ADMIN",

  PRODUCER_REQUEST_CREATE = "PRODUCER_REQUEST_CREATE",

  /** MANAGEMENT */
  CLIENT_CREATE = "CLIENT_CREATE",
  CLIENT_READ = "CLIENT_READ",
  CLIENT_UPDATE = "CLIENT_UPDATE",
  CLIENT_DELETE = "CLIENT_DELETE",

  DATA_LEAK_CREATE = "DATA_LEAK_CREATE",
  DATA_LEAK_READ = "DATA_LEAK_READ",
  DATA_LEAK_UPDATE = "DATA_LEAK_UPDATE",
  DATA_LEAK_DELETE = "DATA_LEAK_DELETE",

  /** SETTINGS */
  ROLE_CREATE = "ROLE_CREATE",
  ROLE_READ = "ROLE_READ",
  ROLE_UPDATE = "ROLE_UPDATE",
  ROLE_DELETE = "ROLE_DELETE",

  USER_CREATE = "USER_CREATE",
  USER_READ = "USER_READ",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",
}
